TOKEN : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlODM0ZWJlNjFhNDQ4OWY2MzI3NmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzEzMjgwMTI0LCJleHAiOjE3MTM4ODQ5MjR9.aYfeVASQnyv3j1NdVBLqS2d3XBOnDzzw6Tzq6VtQegE

#USER
###
POST ${meta.env.VITE_API_URL}/api/users/register
Content-Type: application/json

{
  "username": "Ivan",
  "password": "qwerty123"
}

###
POST ${meta.env.VITE_API_URL}/api/users/login
Content-Type: application/json

{
  "username": "IvanxDev",
  "password": "Qwerty123@"
}



#MENUS
###
POST ${meta.env.VITE_API_URL}/api/menus/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlODM0ZWJlNjFhNDQ4OWY2MzI3NmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzEzMjgwMTI0LCJleHAiOjE3MTM4ODQ5MjR9.aYfeVASQnyv3j1NdVBLqS2d3XBOnDzzw6Tzq6VtQegE
Content-Type: application/json

{
  "title": "Menu Burger Classic",
  "description": "Un delicieux burger classique avec accompagnement et une boisson",
  "price": 9.99,
  "size": "large"
}

###
GET ${meta.env.VITE_API_URL}/api/menus

###
GET ${meta.env.VITE_API_URL}/api/menus/65c23f431690de71b504e218

###
PUT ${meta.env.VITE_API_URL}/api/menus/modify/65c383d44d0919bcffead049
Content-Type: application/json


{
  "type": "Menu"
}

###
DELETE ${meta.env.VITE_API_URL}/api/menus/delete/65c3692f74cec163f3405f2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMzNjJlYjU4OWY3ZTYwOGQwMWQ4YjUiLCJpYXQiOjE3MTAwMTY0OTQsImV4cCI6MTcxMDYyMTI5NH0.fXstxosLDCCKK5GfDycU8bZ_udAi9ddw5O5OJVKiaFk

#PRODUCTS
###
POST ${meta.env.VITE_API_URL}/api/products/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMzNjJlYjU4OWY3ZTYwOGQwMWQ4YjUiLCJpYXQiOjE3MTAwMTY0OTQsImV4cCI6MTcxMDYyMTI5NH0.fXstxosLDCCKK5GfDycU8bZ_udAi9ddw5O5OJVKiaFk
Content-Type: application/json

{
  "title": "Classic Burger",
  "description": "A classic cheese-beef burger",
  "price": 5.99,
  "inStock": true,
  "type": "Burger",
  "imageSrc": "ImagePath"
}

###
GET ${meta.env.VITE_API_URL}/api/products

###
GET ${meta.env.VITE_API_URL}/api/products/65c23f431690de71b504e204

###
PUT ${meta.env.VITE_API_URL}/api/products/modify/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMzNjJlYjU4OWY3ZTYwOGQwMWQ4YjUiLCJpYXQiOjE3MTAwMTY0OTQsImV4cCI6MTcxMDYyMTI5NH0.fXstxosLDCCKK5GfDycU8bZ_udAi9ddw5O5OJVKiaFk
Content-Type: application/json

{
  "price": 6.49,
  "inStock": true
}

###
DELETE ${meta.env.VITE_API_URL}/api/products/delete/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMzNjJlYjU4OWY3ZTYwOGQwMWQ4YjUiLCJpYXQiOjE3MTAwMTY0OTQsImV4cCI6MTcxMDYyMTI5NH0.fXstxosLDCCKK5GfDycU8bZ_udAi9ddw5O5OJVKiaFk


###
POST ${meta.env.VITE_API_URL}/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlODM0ZWJlNjFhNDQ4OWY2MzI3NmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzEzMjgwMTI0LCJleHAiOjE3MTM4ODQ5MjR9.aYfeVASQnyv3j1NdVBLqS2d3XBOnDzzw6Tzq6VtQegE
Content-Type: application/json


{
  "items": [
    {
      "itemRef": "65c23f431690de71b504e204",
      "onModel": "Product",
      "quantity": 2,
      "selectedOptions": {}
    },
    {
      "itemRef": "65c23f431690de71b504e218",
      "onModel": "Menu",
      "quantity": 1,
      "selectedOptions": {}
    }
  ],
  "customer": {
    "name": "Ivan",
    "email": "yohanpetrov@hotmail.fr"
  },
  "totalPrice": 25.97
}

###
POST ${meta.env.VITE_API_URL}/api/orders/add/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlODM0ZWJlNjFhNDQ4OWY2MzI3NmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzEzMjgwMTI0LCJleHAiOjE3MTM4ODQ5MjR9.aYfeVASQnyv3j1NdVBLqS2d3XBOnDzzw6Tzq6VtQegE
Content-Type: application/json

     {
  "items": [
    {
      "itemRef": "65c23f431690de71b504e204",
      "onModel": "Product",
      "quantity": 2,
      "selectedOptions": {}
    },
    {
      "itemRef": "65c23f431690de71b504e218",
      "onModel": "Menu",
      "quantity": 1,
      "selectedOptions": {}
    }
  ],
  "customer": "661e834ebe61a4489f63276e",
  "totalPrice": 25.97
}
