# fly.toml app configuration file generated for back-cold-morning-3477 on 2025-10-02T15:50:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'back-cold-morning-3477'
primary_region = 'cdg'

[build]

[http_service]
 internal_port = 2233
  force_https = true
  auto_stop_machines = 'suspend'  
  auto_start_machines = true
  min_machines_running = 1      
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
